(ns vm.wireguard
  "WireGuard config generation wizard. Produces per-peer wg-quick configs
  (with matched keypairs) for a hub-and-spoke VPN into the hub's machine
  config directory (machines/<hub>/wireguard/), and updates
  machines/<hub>/wireguard.conf so `just upgrade <hub>` applies it.

  Called from vm.cli as the `wireguard-init` command; also exposes
  `generate-keypair!` reused by vm.machine when seeding a machine's initial
  wireguard.conf."
  (:require [clojure.string :as str]
            [clojure.edn :as edn]
            [clojure.pprint :as pp]
            [babashka.fs :as fs]
            [vm.proc :as proc]
            [vm.prompt :as prompt]
            [vm.machine :as machine]))

;; ─── key generation ──────────────────────────────────────────────────────────

(defn generate-keypair!
  "Generate a fresh WireGuard keypair via `nix run nixpkgs#wireguard-tools`.
  Returns {:private <base64> :public <base64>}."
  [cfg]
  (let [priv (proc/capture (concat (:nix cfg) ["run" "nixpkgs#wireguard-tools" "--" "genkey"]))
        pub  (proc/capture (concat (:nix cfg) ["run" "nixpkgs#wireguard-tools" "--" "pubkey"])
                           {:in priv})]
    {:private priv :public pub}))

;; ─── subnet arithmetic ───────────────────────────────────────────────────────

(defn- parse-cidr
  "Parse '10.0.0.0/24' -> {:base [10 0 0 0] :prefix 24}. Throws ex-info on bad input."
  [s]
  (let [t (str/trim (or s ""))
        [addr prefix] (str/split t #"/" 2)]
    (when (str/blank? prefix)
      (throw (ex-info (format "invalid CIDR '%s' (expected e.g. 10.0.0.0/24)" t) {})))
    (let [octets (try (mapv #(Long/parseLong %) (str/split addr #"\."))
                      (catch Exception _ nil))
          p (try (Long/parseLong prefix) (catch Exception _ nil))]
      (when (or (nil? octets) (not= 4 (count octets))
                (some #(or (< % 0) (> % 255)) octets)
                (nil? p) (< p 8) (> p 32))
        (throw (ex-info (format "invalid CIDR '%s' (expected e.g. 10.0.0.0/24)" t) {})))
      {:base octets :prefix p})))

(defn- subnet-str [{:keys [base prefix]}]
  (format "%s/%d" (str/join "." base) prefix))

(defn- suggest-next-ip
  "For a /24 subnet, return 'a.b.c.N' for the smallest N in [1..254] not in
  used-set. nil for prefixes other than /24 (auto-suggestion off; user must type)."
  [subnet used-set]
  (when (= 24 (:prefix subnet))
    (let [[a b c _] (:base subnet)
          used-last (into #{} (keep (fn [ip]
                                      (try (Long/parseLong (last (str/split ip #"\.")))
                                           (catch Exception _ nil)))
                                    used-set))]
      (when-let [n (first (remove used-last (range 1 255)))]
        (format "%d.%d.%d.%d" a b c n)))))

;; ─── config rendering ────────────────────────────────────────────────────────

(defn- render-interface [self]
  (str/join "\n"
            (concat
             ["[Interface]"
              (format "# hostname: %s" (:name self))
              (format "PrivateKey = %s" (:private self))
              (format "Address    = %s/%d" (:address self) (:prefix self))]
             (when-let [port (:listen-port self)]
               [(format "ListenPort = %d" port)]))))

(defn- render-peer-block
  "One [Peer] block for `other` from `self`'s perspective. `allowed-ips` is
  the raw string (e.g. '10.0.0.2/32' or the whole subnet for a spoke pointing
  at its hub)."
  [self other allowed-ips]
  (let [roaming-self? (nil? (:listen-port self))
        listener-other? (some? (:endpoint other))]
    (str/join "\n"
              (concat
               ["[Peer]"
                (format "# hostname: %s" (:name other))
                (format "PublicKey  = %s" (:public other))]
               (when listener-other?
                 [(format "Endpoint   = %s" (:endpoint other))])
               [(format "AllowedIPs = %s" allowed-ips)]
               (when (and roaming-self? listener-other?)
                 ["PersistentKeepalive = 25"])))))

(defn- render-config
  "Full wg-quick config for `self` in a hub-and-spoke topology."
  [subnet self peers]
  (let [banner (str/join "\n"
                         [(format "# WireGuard config for '%s' (interface wg0)." (:name self))
                          (format "# Public key: %s" (:public self))
                          (format "# Generated by `wireguard-init` — subnet %s, topology hub-spoke."
                                  (subnet-str subnet))
                          "# Standard wg-quick format (man wg-quick / man wg)."])
        interface (render-interface self)
        others (remove #(= (:name %) (:name self)) peers)
        peer-blocks
        (if (= :hub (:role self))
          (for [p others] (render-peer-block self p (str (:address p) "/32")))
          (let [hub (first (filter #(= :hub (:role %)) peers))]
            (when-not hub
              (throw (ex-info "hub-and-spoke topology has no hub peer" {})))
            [(render-peer-block self hub (subnet-str subnet))]))]
    (str (str/join "\n\n" (cons banner (cons interface peer-blocks))) "\n")))

;; ─── prompts ─────────────────────────────────────────────────────────────────

(defn- retry
  "Call `f`; if it throws ex-info, print its message and retry. Any other
  exception propagates (bug, not user input error)."
  [f]
  (loop []
    (let [r (try [::ok (f)]
                 (catch clojure.lang.ExceptionInfo e [::retry (ex-message e)]))]
      (if (= ::ok (first r))
        (second r)
        (do (println (format "  ! %s" (second r))) (recur))))))

(defn- valid-peer-name? [s]
  (boolean (re-matches #"[A-Za-z0-9][A-Za-z0-9._-]*" (or s ""))))

(defn- ask-subnet []
  (retry #(parse-cidr (prompt/ask "VPN subnet (CIDR):" "10.0.0.0/24"))))

(defn- parse-port [s]
  (try (let [n (Long/parseLong (str/trim (or s "")))]
         (when (or (< n 1) (> n 65535))
           (throw (ex-info "port out of range" {})))
         n)
       (catch NumberFormatException _
         (throw (ex-info (format "invalid port '%s'" s) {})))))

(defn- ask-hub
  "Prompt for the hub peer's listener details. `name` is the hub's peer name
  (matches its VM machine dir) and is not prompted for."
  [subnet name]
  (retry
   (fn []
     (let [listen-port (parse-port (prompt/ask
                                    (format "ListenPort for '%s' (UDP):" name) "51820"))
           endpoint (let [h (str/trim (prompt/ask
                                       (format "Public Endpoint for '%s' (host or IP that peers dial):" name)))]
                      (when (str/blank? h)
                        (throw (ex-info "endpoint host is required for the hub" {})))
                      (format "%s:%d" h listen-port))
           suggested (suggest-next-ip subnet #{})
           addr-in (str/trim (prompt/ask
                              (format "Tunnel address for '%s' (inside %s):" name (subnet-str subnet))
                              suggested))]
       (when (str/blank? addr-in) (throw (ex-info "tunnel address is required" {})))
       (when-not (re-matches #"\d+\.\d+\.\d+\.\d+" addr-in)
         (throw (ex-info (format "address '%s' must be a bare IPv4 (no /prefix)" addr-in) {})))
       {:name name :role :hub :address addr-in
        :prefix (:prefix subnet) :listen-port listen-port :endpoint endpoint}))))

(defn- ask-spoke
  "Prompt for one spoke peer. `existing` are already-added peers so we can
  suggest the next address and prevent name/address collisions."
  [subnet existing]
  (retry
   (fn []
     (let [name (str/trim (prompt/ask "Peer name (used as filename and comment):"))]
       (when (str/blank? name) (throw (ex-info "peer name is required" {})))
       (when-not (valid-peer-name? name)
         (throw (ex-info "peer name must start alphanumeric; only letters, digits, . _ -" {})))
       (when (some #(= (:name %) name) existing)
         (throw (ex-info (format "peer name '%s' already used" name) {})))
       (let [used-addrs (into #{} (map :address existing))
             suggested (suggest-next-ip subnet used-addrs)
             addr-in (str/trim (prompt/ask
                                (format "Tunnel address for '%s' (inside %s):" name (subnet-str subnet))
                                suggested))]
         (when (str/blank? addr-in) (throw (ex-info "tunnel address is required" {})))
         (when (contains? used-addrs addr-in)
           (throw (ex-info (format "address %s already assigned to another peer" addr-in) {})))
         (when-not (re-matches #"\d+\.\d+\.\d+\.\d+" addr-in)
           (throw (ex-info (format "address '%s' must be a bare IPv4 (no /prefix)" addr-in) {})))
         {:name name :role :spoke :address addr-in
          :prefix (:prefix subnet) :listen-port nil :endpoint nil})))))

(defn- summarize-peer [p]
  (format "  %-16s  %s%s%s"
          (:name p)
          (:address p)
          (case (:role p)
            :hub      "  [hub]"
            :spoke    "  [spoke]"
            "")
          (if (:endpoint p) (str "  -> " (:endpoint p)) "")))

;; ─── state file ──────────────────────────────────────────────────────────────

(def ^:private state-version 2)
(defn- state-path [out-dir] (str out-dir "/.wg-state.edn"))

(defn- write-state!
  "Persist subnet + peer metadata to .wg-state.edn. Private keys are never
  written here — they stay in <peer>.key. `add-peer-wizard` reads this file to
  rebuild every peer's config when connecting a new peer."
  [out-dir subnet peers]
  (let [scrubbed (mapv #(select-keys % [:name :role :address :prefix
                                        :listen-port :endpoint :public])
                       peers)
        data {:version state-version
              :subnet (subnet-str subnet)
              :topology :hub-spoke
              :peers scrubbed}]
    (fs/create-dirs out-dir)
    (spit (state-path out-dir)
          (binding [*print-namespace-maps* false]
            (with-out-str (pp/pprint data))))))

(defn- load-state-or-exit!
  "Read .wg-state.edn from an existing dir, or print + exit 1 on any problem."
  [out-dir hub-name]
  (cond
    (not (fs/directory? out-dir))
    (do (println (format "Error: '%s' does not exist." out-dir))
        (println (format "  Run 'just wireguard-init %s' first." hub-name))
        (System/exit 1))

    (not (fs/exists? (state-path out-dir)))
    (do (println (format "Error: no .wg-state.edn in %s" out-dir))
        (println (format "  Run 'just wireguard-init %s' to create it." hub-name))
        (System/exit 1))

    :else
    (let [p (state-path out-dir)
          data (try (edn/read-string (slurp p))
                    (catch Exception e
                      (println (format "Error: failed to parse %s: %s" p (ex-message e)))
                      (System/exit 1)))]
      (when-not (contains? #{1 2} (:version data))
        (println (format "Error: unsupported .wg-state.edn version in %s (found %s, expected %d)"
                         p (:version data) state-version))
        (System/exit 1))
      data)))

(defn- rehydrate-peer!
  "Attach an existing peer's private key (read from <peer>.key on disk) so it
  can be re-rendered. Exits with a clear error if the .key file is missing."
  [out-dir peer]
  (let [name (:name peer)
        kp (str out-dir "/" name ".key")]
    (when-not (fs/exists? kp)
      (println (format "Error: state file lists peer '%s' but %s is missing." name kp))
      (println "  Cannot regenerate configs without the private key. Restore it from a")
      (println "  backup-* subdirectory or delete the wireguard/ dir and re-run wireguard-init.")
      (System/exit 1))
    (assoc peer :private (str/trim (slurp kp)))))

;; ─── backup ──────────────────────────────────────────────────────────────────

(defn- ts-stamp []
  (.format (java.time.LocalDateTime/now)
           (java.time.format.DateTimeFormatter/ofPattern "yyyyMMdd-HHmmss")))

(defn- backup-existing!
  "Move every existing .conf/.key/.pub/README.txt/.wg-state.edn in `out-dir`,
  plus the hub's `<parent>/wireguard.conf` (identity file), into
  `out-dir/backup-<ts>/`. Returns the backup dir path, or nil if there was
  nothing to move."
  [out-dir hub-conf]
  (let [backup-dir (str out-dir "/backup-" (ts-stamp))
        globbed (when (fs/directory? out-dir)
                  (concat (map str (fs/glob out-dir "*.conf"))
                          (map str (fs/glob out-dir "*.key"))
                          (map str (fs/glob out-dir "*.pub"))))
        extras (filter fs/exists? [(str out-dir "/README.txt")
                                   (state-path out-dir)
                                   hub-conf])
        all (concat globbed extras)]
    (when (seq all)
      (fs/create-dirs backup-dir)
      (doseq [src all]
        (fs/move src (str backup-dir "/" (fs/file-name src)) {:replace-existing true}))
      backup-dir)))

;; ─── file writing / apply ────────────────────────────────────────────────────

(defn- write-peer-files!
  "Write <peer>.key/.pub/.conf into `out-dir`. Sets 0600 on private key + conf."
  [out-dir subnet peers]
  (fs/create-dirs out-dir)
  (doseq [self peers
          :let [name (:name self)
                key-path  (str out-dir "/" name ".key")
                pub-path  (str out-dir "/" name ".pub")
                conf-path (str out-dir "/" name ".conf")]]
    (spit key-path (str (:private self) "\n"))
    (fs/set-posix-file-permissions key-path "rw-------")
    (spit pub-path (str (:public self) "\n"))
    (spit conf-path (render-config subnet self peers))
    (fs/set-posix-file-permissions conf-path "rw-------")
    (println (format "  wrote %s.{key,pub,conf}" name))))

(defn- write-readme! [out-dir subnet hub-name peers]
  (let [lines
        (concat
         [(format "WireGuard configs — subnet %s, topology hub-spoke, hub '%s'."
                  (subnet-str subnet) hub-name)
          ""
          "Files per peer:"
          "  <peer>.key   private key  (mode 0600)"
          "  <peer>.pub   public key   (share)"
          "  <peer>.conf  wg-quick config  (mode 0600)"
          ""
          (format "The hub's config is already applied at machines/%s/wireguard.conf." hub-name)
          (format "Run 'just upgrade %s' to push it into the VM." hub-name)
          ""
          "Deploying a spoke config:"
          "  * A VM in this repo:   copy <peer>.conf to  machines/<peer>/wireguard.conf"
          "                          then  just upgrade <peer>"
          "                          (the wizard offers to do this for you)."
          "  * A generic Linux box: copy <peer>.conf to  /etc/wireguard/wg0.conf  (mode 0600)"
          "                          then  sudo wg-quick up wg0"
          "                                sudo systemctl enable wg-quick@wg0"
          "  * A phone (WireGuard app): import <peer>.conf, or scan its QR."
          ""
          "Peers:"]
         (map summarize-peer peers)
         [""
          "Notes:"
          " * Spoke configs route the whole VPN subnet through the hub."
          " * The hub must have UDP <ListenPort> reachable from the internet"
          "   (port-forward on the router if behind NAT)."
          " * On this repo's VMs the wireguard profile already opens UDP 51820;"
          "   change udp_ports if you use a different ListenPort."
          ""
          (format "Add another peer later:  just wireguard-add-peer %s" hub-name)
          ""])]
    (spit (str out-dir "/README.txt") (str/join "\n" lines))))

(defn- write-hub-conf!
  "Copy the hub's generated <hub>.conf to machines/<hub>/wireguard.conf so
  identity sync picks it up. The wireguard/ dir remains the source of truth."
  [cfg hub-name out-dir]
  (let [src (str out-dir "/" hub-name ".conf")
        dst (str (machine/machine-dir cfg hub-name) "/wireguard.conf")]
    (fs/copy src dst {:replace-existing true})
    (fs/set-posix-file-permissions dst "rw-------")
    (println (format "  applied -> %s" dst))
    (println (format "    run: just upgrade %s" hub-name))))

(defn- offer-apply-spokes!
  "For every spoke whose name matches an existing machine dir, ask whether to
  copy the generated .conf into machines/<name>/wireguard.conf."
  [cfg out-dir peers]
  (let [known (into #{} (map :name (machine/list-machines cfg)))
        spokes (filter #(= :spoke (:role %)) peers)
        matches (filter #(contains? known (:name %)) spokes)]
    (when (seq matches)
      (println)
      (println (format "Detected %d spoke peer name(s) that match existing machines in %s:"
                       (count matches) (:machines-dir cfg)))
      (doseq [p matches] (println (format "  %s" (:name p))))
      (println)
      (when (prompt/confirm "Copy those .conf files into their machines/<name>/wireguard.conf?" :yes)
        (doseq [p matches
                :let [name (:name p)
                      src (str out-dir "/" name ".conf")
                      dst (str (machine/machine-dir cfg name) "/wireguard.conf")]]
          (when (or (not (fs/exists? dst))
                    (prompt/confirm (format "%s already exists — overwrite?" dst) :no))
            (fs/copy src dst {:replace-existing true})
            (fs/set-posix-file-permissions dst "rw-------")
            (println (format "  copied -> %s" dst))
            (println (format "    run: just upgrade %s" name))))))))

;; ─── main entrypoints ────────────────────────────────────────────────────────

(defn- require-name! [name usage]
  (when (or (nil? name) (str/blank? name))
    (println "Error: hub VM name is required.")
    (println (str "Usage: " usage))
    (System/exit 1)))

(defn- require-machine! [cfg name]
  (when-not (machine/exists? cfg name)
    (println (format "Error: no machine config at %s." (machine/machine-dir cfg name)))
    (println (format "  Create it first:  just create %s wireguard" name))
    (System/exit 1)))

(defn- out-dir-for [cfg name]
  (str (machine/machine-dir cfg name) "/wireguard"))

(defn- hub-conf-for [cfg name]
  (str (machine/machine-dir cfg name) "/wireguard.conf"))

(defn- write-all!
  "Write per-peer files, README, and state file. Common tail of both wizards."
  [cfg hub-name out-dir subnet peers]
  (write-peer-files! out-dir subnet peers)
  (write-readme! out-dir subnet hub-name peers)
  (write-state! out-dir subnet peers)
  (println "  wrote README.txt and .wg-state.edn")
  (write-hub-conf! cfg hub-name out-dir))

(defn wizard
  "Interactive `wireguard-init <hub>`: prompt for subnet and peer list, then
  generate keypairs and wg-quick configs into machines/<hub>/wireguard/. The
  hub's own config is copied to machines/<hub>/wireguard.conf so
  `just upgrade <hub>` applies it. For spoke peer names that match other
  machine dirs, the wizard offers to apply their configs too."
  [cfg name]
  (require-name! name "just wireguard-init <hub>")
  (require-machine! cfg name)
  (let [out-dir (out-dir-for cfg name)
        hub-conf (hub-conf-for cfg name)]
    (when (fs/exists? (state-path out-dir))
      (println (format "Error: %s already exists." (state-path out-dir)))
      (println (format "  Add a peer with:  just wireguard-add-peer %s" name))
      (println (format "  Or delete %s to start over." out-dir))
      (System/exit 1))
    (println "WireGuard config wizard")
    (println (format "  Hub VM:  %s" name))
    (println (format "  Output:  %s/" out-dir))
    (println "  Generates matched keypairs and wg-quick configs for a hub-and-spoke VPN.")
    (println "  Nothing is written until you confirm the plan.")
    (println)
    (let [subnet (ask-subnet)
          _ (println (format "Subnet: %s" (subnet-str subnet)))
          _ (when-not (= 24 (:prefix subnet))
              (println "  (auto-address suggestion is disabled for non-/24 subnets — type the address manually)"))
          _ (println)
          _ (println (format "── Hub peer '%s' ─────────────────────────" name))
          hub (ask-hub subnet name)
          _ (println (summarize-peer hub))
          _ (println)
          _ (println "Now add the spoke peers.")
          peers
          (loop [acc [hub]]
            (println (format "── Spoke %d ─────────────────────────" (count acc)))
            (let [p (ask-spoke subnet acc)
                  acc' (conj acc p)]
              (println (summarize-peer p))
              (println)
              (if (and (>= (count acc') 2)
                       (not (prompt/confirm "Add another peer?" :yes)))
                acc'
                (recur acc'))))]
      (println)
      (println "Plan:")
      (println (format "  Subnet:   %s" (subnet-str subnet)))
      (println (format "  Hub:      %s" name))
      (println (format "  Peers:    %d" (count peers)))
      (doseq [p peers] (println (summarize-peer p)))
      (println (format "  Output:   %s" out-dir))
      (println (format "  Hub cfg:  %s" hub-conf))
      (println)
      (when-not (prompt/confirm "Generate keys and write files?" :yes)
        (println "Aborted.")
        (System/exit 0))
      (println)
      (println "Generating keypairs...")
      (let [peers-kp (mapv (fn [p] (merge p (generate-keypair! cfg))) peers)]
        (println)
        (when-let [b (backup-existing! out-dir hub-conf)]
          (println (format "Backed up previous files -> %s" b)))
        (println (format "Writing configs to %s" out-dir))
        (write-all! cfg name out-dir subnet peers-kp)
        (offer-apply-spokes! cfg out-dir peers-kp)
        (println)
        (println "Done.")
        (println (format "  Hub state:  %s/" out-dir))
        (println "  See README.txt for how to deploy each spoke's config.")
        (println (format "  Add another peer later: just wireguard-add-peer %s" name))))))

(defn add-peer-wizard
  "Interactive `wireguard-add-peer <hub>`: load state from
  machines/<hub>/wireguard/.wg-state.edn, prompt for one new spoke peer, back
  up the existing files, and regenerate every peer's config (so the new peer
  is fully connected). Then rewrite the state file, reapply the hub's
  wireguard.conf, and offer to apply any changed spoke configs to matching
  machines/<name>/wireguard.conf entries."
  [cfg name]
  (require-name! name "just wireguard-add-peer <hub>")
  (require-machine! cfg name)
  (let [out-dir (out-dir-for cfg name)
        hub-conf (hub-conf-for cfg name)
        state (load-state-or-exit! out-dir name)
        subnet (parse-cidr (:subnet state))
        existing (vec (:peers state))]
    (println "WireGuard add-peer wizard")
    (println (format "  Hub VM:  %s" name))
    (println (format "  State:   %s" (state-path out-dir)))
    (println "  Adds one spoke peer; every peer's config is regenerated so the new")
    (println "  peer is fully connected. Previous files are moved into a")
    (println "  backup-<timestamp>/ subdir first.")
    (println)
    (println (format "  Subnet:   %s" (:subnet state)))
    (println (format "  Peers:    %d" (count existing)))
    (doseq [p existing] (println (summarize-peer p)))
    (println)
    (println "── New spoke ─────────────────────────")
    (let [new-peer (ask-spoke subnet existing)]
      (println (summarize-peer new-peer))
      (println)
      (println "Plan:")
      (println (format "  Add:      %s" (:name new-peer)))
      (println (format "  Regen:    every peer in %s (%d file(s))" out-dir (inc (count existing))))
      (println (format "  Backup:   %s/backup-<timestamp>/" out-dir))
      (println)
      (when-not (prompt/confirm "Proceed?" :yes)
        (println "Aborted.")
        (System/exit 0))
      (println)
      (println "Generating keypair for new peer...")
      (let [new-kp (merge new-peer (generate-keypair! cfg))
            existing-hydrated (mapv #(rehydrate-peer! out-dir %) existing)
            all-peers (conj existing-hydrated new-kp)
            backup-dir (backup-existing! out-dir hub-conf)]
        (when backup-dir
          (println (format "  backed up previous files -> %s" backup-dir)))
        (println (format "Writing configs to %s" out-dir))
        (write-all! cfg name out-dir subnet all-peers)
        (offer-apply-spokes! cfg out-dir all-peers)
        (println)
        (println "Done.")
        (println (format "  New peer:  %s (%s)" (:name new-kp) (:address new-kp)))
        (println (format "  Backup:    %s" (or backup-dir "(nothing to back up)")))
        (println "  Existing peers' configs also changed — redeploy any peers you didn't apply.")))))
