(ns vm.wireguard
  "WireGuard config generation wizard. Produces per-peer wg-quick configs
  (with matched keypairs) for a hub-and-spoke or full-mesh topology into an
  output directory, and optionally copies each config into a matching
  machines/<name>/wireguard.conf so `just upgrade <name>` applies it.

  Called from vm.cli as the `wireguard-init` command; also exposes
  `generate-keypair!` reused by vm.machine when seeding a machine's initial
  wireguard.conf."
  (:require [clojure.string :as str]
            [clojure.edn :as edn]
            [clojure.pprint :as pp]
            [babashka.fs :as fs]
            [vm.proc :as proc]
            [vm.prompt :as prompt]
            [vm.machine :as machine]))

;; ─── key generation ──────────────────────────────────────────────────────────

(defn generate-keypair!
  "Generate a fresh WireGuard keypair via `nix run nixpkgs#wireguard-tools`.
  Returns {:private <base64> :public <base64>}."
  [cfg]
  (let [priv (proc/capture (concat (:nix cfg) ["run" "nixpkgs#wireguard-tools" "--" "genkey"]))
        pub  (proc/capture (concat (:nix cfg) ["run" "nixpkgs#wireguard-tools" "--" "pubkey"])
                           {:in priv})]
    {:private priv :public pub}))

;; ─── subnet arithmetic ───────────────────────────────────────────────────────

(defn- parse-cidr
  "Parse '10.0.0.0/24' -> {:base [10 0 0 0] :prefix 24}. Throws ex-info on bad input."
  [s]
  (let [t (str/trim (or s ""))
        [addr prefix] (str/split t #"/" 2)]
    (when (str/blank? prefix)
      (throw (ex-info (format "invalid CIDR '%s' (expected e.g. 10.0.0.0/24)" t) {})))
    (let [octets (try (mapv #(Long/parseLong %) (str/split addr #"\."))
                      (catch Exception _ nil))
          p (try (Long/parseLong prefix) (catch Exception _ nil))]
      (when (or (nil? octets) (not= 4 (count octets))
                (some #(or (< % 0) (> % 255)) octets)
                (nil? p) (< p 8) (> p 32))
        (throw (ex-info (format "invalid CIDR '%s' (expected e.g. 10.0.0.0/24)" t) {})))
      {:base octets :prefix p})))

(defn- subnet-str [{:keys [base prefix]}]
  (format "%s/%d" (str/join "." base) prefix))

(defn- suggest-next-ip
  "For a /24 subnet, return 'a.b.c.N' for the smallest N in [1..254] not in
  used-set. nil for prefixes other than /24 (auto-suggestion off; user must type)."
  [subnet used-set]
  (when (= 24 (:prefix subnet))
    (let [[a b c _] (:base subnet)
          used-last (into #{} (keep (fn [ip]
                                      (try (Long/parseLong (last (str/split ip #"\.")))
                                           (catch Exception _ nil)))
                                    used-set))]
      (when-let [n (first (remove used-last (range 1 255)))]
        (format "%d.%d.%d.%d" a b c n)))))

;; ─── config rendering ────────────────────────────────────────────────────────

(defn- render-interface [self]
  (str/join "\n"
            (concat
             ["[Interface]"
              (format "# hostname: %s" (:name self))
              (format "PrivateKey = %s" (:private self))
              (format "Address    = %s/%d" (:address self) (:prefix self))]
             (when-let [port (:listen-port self)]
               [(format "ListenPort = %d" port)]))))

(defn- render-peer-block
  "One [Peer] block for `other` from `self`'s perspective. `allowed-ips` is
  the raw string (e.g. '10.0.0.2/32' or the whole subnet for a spoke pointing
  at its hub)."
  [self other allowed-ips]
  (let [roaming-self? (nil? (:listen-port self))
        listener-other? (some? (:endpoint other))]
    (str/join "\n"
              (concat
               ["[Peer]"
                (format "# hostname: %s" (:name other))
                (format "PublicKey  = %s" (:public other))]
               (when listener-other?
                 [(format "Endpoint   = %s" (:endpoint other))])
               [(format "AllowedIPs = %s" allowed-ips)]
               (when (and roaming-self? listener-other?)
                 ["PersistentKeepalive = 25"])))))

(defn- render-config
  "Full wg-quick config for `self`. `topology` is :hub-spoke or :mesh."
  [subnet topology self peers]
  (let [banner (str/join "\n"
                         [(format "# WireGuard config for '%s' (interface wg0)." (:name self))
                          (format "# Public key: %s" (:public self))
                          (format "# Generated by `wireguard-init` — subnet %s, topology %s."
                                  (subnet-str subnet) (name topology))
                          "# Standard wg-quick format (man wg-quick / man wg)."])
        interface (render-interface self)
        others (remove #(= (:name %) (:name self)) peers)
        peer-blocks
        (case topology
          :hub-spoke
          (if (= :hub (:role self))
            (for [p others] (render-peer-block self p (str (:address p) "/32")))
            (let [hub (first (filter #(= :hub (:role %)) peers))]
              (when-not hub
                (throw (ex-info "hub-and-spoke topology has no hub peer" {})))
              [(render-peer-block self hub (subnet-str subnet))]))
          :mesh
          (for [p others] (render-peer-block self p (str (:address p) "/32"))))]
    (str (str/join "\n\n" (cons banner (cons interface peer-blocks))) "\n")))

;; ─── prompts ─────────────────────────────────────────────────────────────────

(defn- retry
  "Call `f`; if it throws ex-info, print its message and retry. Any other
  exception propagates (bug, not user input error)."
  [f]
  (loop []
    (let [r (try [::ok (f)]
                 (catch clojure.lang.ExceptionInfo e [::retry (ex-message e)]))]
      (if (= ::ok (first r))
        (second r)
        (do (println (format "  ! %s" (second r))) (recur))))))

(defn- valid-peer-name? [s]
  (boolean (re-matches #"[A-Za-z0-9][A-Za-z0-9._-]*" (or s ""))))

(defn- ask-subnet []
  (retry #(parse-cidr (prompt/ask "VPN subnet (CIDR):" "10.0.0.0/24"))))

(defn- ask-topology []
  (let [c (prompt/choose "Topology:"
                         ["Hub-and-spoke (one listener, spokes route through it)"
                          "Full mesh (every peer connects to every other)"])]
    (if (str/starts-with? c "Hub") :hub-spoke :mesh)))

(defn- ask-peer
  "Prompt for one peer's details. `existing` are already-added peers so we can
  suggest the next address and prevent name/address collisions."
  [subnet topology existing]
  (retry
   (fn []
     (let [name (str/trim (prompt/ask "Peer name (used as filename and comment):"))]
       (when (str/blank? name) (throw (ex-info "peer name is required" {})))
       (when-not (valid-peer-name? name)
         (throw (ex-info "peer name must start alphanumeric; only letters, digits, . _ -" {})))
       (when (some #(= (:name %) name) existing)
         (throw (ex-info (format "peer name '%s' already used" name) {})))
       (let [hub? (and (= topology :hub-spoke) (empty? existing))
             role (cond
                    hub? :hub
                    (= topology :hub-spoke) :spoke
                    :else (if (prompt/confirm
                               (format "Is '%s' a listener (has a public Endpoint others dial in to)?" name)
                               :no)
                            :listener :roaming))
             listener? (contains? #{:hub :listener} role)
             listen-port (when listener?
                           (let [p (str/trim (prompt/ask
                                              (format "ListenPort for '%s' (UDP):" name) "51820"))]
                             (try (let [n (Long/parseLong p)]
                                    (when (or (< n 1) (> n 65535))
                                      (throw (ex-info "port out of range" {})))
                                    n)
                                  (catch Exception _
                                    (throw (ex-info (format "invalid port '%s'" p) {}))))))
             endpoint (when listener?
                        (let [h (str/trim (prompt/ask
                                           (format "Public Endpoint for '%s' (host or IP that peers dial):" name)))]
                          (when (str/blank? h)
                            (throw (ex-info "endpoint host is required for a listener" {})))
                          (format "%s:%d" h listen-port)))
             used-addrs (into #{} (map :address existing))
             suggested (suggest-next-ip subnet used-addrs)
             addr-in (str/trim (prompt/ask
                                (format "Tunnel address for '%s' (inside %s):" name (subnet-str subnet))
                                suggested))]
         (when (str/blank? addr-in) (throw (ex-info "tunnel address is required" {})))
         (when (contains? used-addrs addr-in)
           (throw (ex-info (format "address %s already assigned to another peer" addr-in) {})))
         (when-not (re-matches #"\d+\.\d+\.\d+\.\d+" addr-in)
           (throw (ex-info (format "address '%s' must be a bare IPv4 (no /prefix)" addr-in) {})))
         {:name name :role role :address addr-in
          :prefix (:prefix subnet) :listen-port listen-port :endpoint endpoint})))))

(defn- summarize-peer [p]
  (format "  %-16s  %s%s%s"
          (:name p)
          (:address p)
          (case (:role p)
            :hub      "  [hub]"
            :listener "  [listener]"
            :roaming  "  [roaming]"
            :spoke    "  [spoke]"
            "")
          (if (:endpoint p) (str "  -> " (:endpoint p)) "")))

;; ─── state file ──────────────────────────────────────────────────────────────

(def ^:private state-version 1)
(defn- state-path [out-dir] (str out-dir "/.wg-state.edn"))

(defn- write-state!
  "Persist subnet + topology + peer metadata to .wg-state.edn. Private keys are
  never written here — they stay in <peer>.key. `add-peer` reads this file to
  rebuild every peer's config when connecting a new peer."
  [out-dir subnet topology peers]
  (let [scrubbed (mapv #(select-keys % [:name :role :address :prefix
                                        :listen-port :endpoint :public])
                       peers)
        data {:version state-version
              :subnet (subnet-str subnet)
              :topology topology
              :peers scrubbed}]
    (fs/create-dirs out-dir)
    (spit (state-path out-dir)
          (binding [*print-namespace-maps* false]
            (with-out-str (pp/pprint data))))))

(defn- load-state-or-exit!
  "Read .wg-state.edn from an existing dir, or print + exit 1 on any problem."
  [out-dir]
  (cond
    (not (fs/directory? out-dir))
    (do (println (format "Error: '%s' is not a directory." out-dir))
        (System/exit 1))

    (not (fs/exists? (state-path out-dir)))
    (do (println (format "Error: no .wg-state.edn in %s" out-dir))
        (println "  (this directory wasn't produced by `just wireguard-init`)")
        (println "  Run `just wireguard-init` to create a fresh set.")
        (System/exit 1))

    :else
    (let [p (state-path out-dir)
          data (try (edn/read-string (slurp p))
                    (catch Exception e
                      (println (format "Error: failed to parse %s: %s" p (ex-message e)))
                      (System/exit 1)))]
      (when-not (= state-version (:version data))
        (println (format "Error: unsupported .wg-state.edn version in %s (found %s, expected %d)"
                         p (:version data) state-version))
        (System/exit 1))
      data)))

(defn- rehydrate-peer!
  "Attach an existing peer's private key (read from <peer>.key on disk) so it
  can be re-rendered. Exits with a clear error if the .key file is missing."
  [out-dir peer]
  (let [name (:name peer)
        kp (str out-dir "/" name ".key")]
    (when-not (fs/exists? kp)
      (println (format "Error: state file lists peer '%s' but %s is missing." name kp))
      (println "  Cannot regenerate configs without the private key. Restore it from a")
      (println "  backup-* subdirectory or start over with `just wireguard-init`.")
      (System/exit 1))
    (assoc peer :private (str/trim (slurp kp)))))

;; ─── backup ──────────────────────────────────────────────────────────────────

(defn- ts-stamp []
  (.format (java.time.LocalDateTime/now)
           (java.time.format.DateTimeFormatter/ofPattern "yyyyMMdd-HHmmss")))

(defn- backup-existing!
  "Move every existing .conf/.key/.pub/README.txt/.wg-state.edn in `out-dir`
  into `out-dir/backup-<ts>/`. Returns the backup dir path, or nil if there
  was nothing to move."
  [out-dir]
  (let [backup-dir (str out-dir "/backup-" (ts-stamp))
        globbed (concat (map str (fs/glob out-dir "*.conf"))
                        (map str (fs/glob out-dir "*.key"))
                        (map str (fs/glob out-dir "*.pub")))
        extras (filter fs/exists? [(str out-dir "/README.txt")
                                   (state-path out-dir)])
        all (concat globbed extras)]
    (when (seq all)
      (fs/create-dirs backup-dir)
      (doseq [src all]
        (fs/move src (str backup-dir "/" (fs/file-name src)) {:replace-existing true}))
      backup-dir)))

;; ─── file writing / apply ────────────────────────────────────────────────────

(defn- write-peer-files!
  "Write <peer>.key/.pub/.conf into `out-dir`. Sets 0600 on private key + conf."
  [out-dir subnet topology peers]
  (fs/create-dirs out-dir)
  (doseq [self peers
          :let [name (:name self)
                key-path  (str out-dir "/" name ".key")
                pub-path  (str out-dir "/" name ".pub")
                conf-path (str out-dir "/" name ".conf")]]
    (spit key-path (str (:private self) "\n"))
    (fs/set-posix-file-permissions key-path "rw-------")
    (spit pub-path (str (:public self) "\n"))
    (spit conf-path (render-config subnet topology self peers))
    (fs/set-posix-file-permissions conf-path "rw-------")
    (println (format "  wrote %s.{key,pub,conf}" name))))

(defn- write-readme! [out-dir subnet topology peers]
  (let [lines
        (concat
         [(format "WireGuard configs — subnet %s, topology %s." (subnet-str subnet) (name topology))
          ""
          "Files per peer:"
          "  <peer>.key   private key  (mode 0600)"
          "  <peer>.pub   public key   (share)"
          "  <peer>.conf  wg-quick config  (mode 0600)"
          ""
          "Deploying a config:"
          "  * A VM in this repo:   copy <peer>.conf to  machines/<peer>/wireguard.conf"
          "                          then  just upgrade <peer>"
          "  * A generic Linux box: copy <peer>.conf to  /etc/wireguard/wg0.conf  (mode 0600)"
          "                          then  sudo wg-quick up wg0"
          "                                sudo systemctl enable wg-quick@wg0"
          "  * A phone (WireGuard app): import <peer>.conf, or scan its QR."
          ""
          "Peers:"]
         (map summarize-peer peers)
         [""
          "Notes:"
          " * Hub-and-spoke: spoke configs route the whole VPN subnet through the hub."
          "   Full mesh: each peer talks directly to every other peer."
          " * Listeners must have UDP <ListenPort> reachable from the internet"
          "   (port-forward on the router if behind NAT)."
          " * On this repo's VMs the wireguard profile already opens UDP 51820;"
          "   change udp_ports if you use a different ListenPort."
          ""])]
    (spit (str out-dir "/README.txt") (str/join "\n" lines))))

(defn- offer-apply!
  "For every peer whose name matches an existing machine dir, ask whether to
  copy the generated .conf into machines/<name>/wireguard.conf."
  [cfg out-dir peers]
  (let [known (into #{} (map :name (machine/list-machines cfg)))
        matches (filter #(contains? known (:name %)) peers)]
    (when (seq matches)
      (println)
      (println (format "Detected %d peer name(s) that match existing machines in %s:"
                       (count matches) (:machines-dir cfg)))
      (doseq [p matches] (println (format "  %s" (:name p))))
      (println)
      (when (prompt/confirm "Copy those .conf files into their machines/<name>/wireguard.conf?" :yes)
        (doseq [p matches
                :let [name (:name p)
                      src (str out-dir "/" name ".conf")
                      dst (str (machine/machine-dir cfg name) "/wireguard.conf")]]
          (when (or (not (fs/exists? dst))
                    (prompt/confirm (format "%s already exists — overwrite?" dst) :no))
            (fs/copy src dst {:replace-existing true})
            (fs/set-posix-file-permissions dst "rw-------")
            (println (format "  copied -> %s" dst))
            (println (format "    run: just upgrade %s" name))))))))

;; ─── main entrypoints ────────────────────────────────────────────────────────

(defn- invocation-cwd
  "Directory to use as the default output location. Prefer $PWD (set by bash),
  fall back to Java's user.dir. Rewrite to $HOME (or /tmp) when the result
  lands under /nix/store — that happens when bb is launched via `nix develop
  --command` from a flake pinned in the store (e.g. `just -d $NIXOS_VM_TEMPLATE`
  where NIXOS_VM_TEMPLATE points at a store path), and the store is read-only."
  []
  (let [candidate (or (some-> (System/getenv "PWD") not-empty)
                      (System/getProperty "user.dir"))]
    (if (str/starts-with? (or candidate "") "/nix/store/")
      (or (some-> (System/getenv "HOME") not-empty) "/tmp")
      candidate)))

(defn- default-out-dir []
  (str (invocation-cwd) "/wireguard-" (ts-stamp)))

(defn- detect-latest-out-dir
  "Newest ./wireguard-*/ in the invocation CWD that carries a .wg-state.edn,
  or nil."
  []
  (let [cwd (invocation-cwd)]
    (some->> (fs/glob cwd "wireguard-*")
             (filter fs/directory?)
             (filter #(fs/exists? (state-path (str %))))
             (sort-by #(str (fs/last-modified-time %)))
             reverse
             first
             str)))

(defn- write-all!
  "Write per-peer files, README, and state file. Common tail of both wizards."
  [out-dir subnet topology peers]
  (write-peer-files! out-dir subnet topology peers)
  (write-readme! out-dir subnet topology peers)
  (write-state! out-dir subnet topology peers)
  (println "  wrote README.txt and .wg-state.edn"))

(defn wizard
  "Interactive `wireguard-init`: prompt for subnet, topology, peer list; then
  generate keypairs and wg-quick configs into an output directory. If any peer
  name matches an existing machine dir, offer to apply the config in place."
  [cfg]
  (println "WireGuard config wizard")
  (println "  Generates matched keypairs and wg-quick configs for a set of peers.")
  (println "  Nothing is written until you confirm the plan.")
  (println)
  (let [subnet (ask-subnet)
        _ (println (format "Subnet: %s" (subnet-str subnet)))
        _ (when-not (= 24 (:prefix subnet))
            (println "  (auto-address suggestion is disabled for non-/24 subnets — type the address manually)"))
        _ (println)
        topology (ask-topology)
        _ (println (format "Topology: %s" (name topology)))
        _ (println)
        peers
        (loop [acc []]
          (println (format "── Peer %d ─────────────────────────" (inc (count acc))))
          (let [p (ask-peer subnet topology acc)
                acc' (conj acc p)]
            (println (summarize-peer p))
            (println)
            (cond
              (and (= topology :hub-spoke) (empty? acc))
              (do (println "Now add the spoke peers.") (recur acc'))

              (< (count acc') 2)
              (recur acc')

              (prompt/confirm "Add another peer?" :yes)
              (recur acc')

              :else acc')))
        out-dir (str/trim (prompt/ask "Output directory:" (default-out-dir)))]
    (println)
    (println "Plan:")
    (println (format "  Subnet:   %s" (subnet-str subnet)))
    (println (format "  Topology: %s" (name topology)))
    (println (format "  Peers:    %d" (count peers)))
    (doseq [p peers] (println (summarize-peer p)))
    (println (format "  Output:   %s" out-dir))
    (println)
    (when-not (prompt/confirm "Generate keys and write files?" :yes)
      (println "Aborted.")
      (System/exit 0))
    (when (fs/exists? out-dir)
      (when-not (prompt/confirm (format "%s already exists — write into it anyway?" out-dir) :no)
        (println "Aborted.") (System/exit 0)))
    (println)
    (println "Generating keypairs...")
    (let [peers-kp (mapv (fn [p] (merge p (generate-keypair! cfg))) peers)]
      (println)
      (println (format "Writing configs to %s" out-dir))
      (write-all! out-dir subnet topology peers-kp)
      (offer-apply! cfg out-dir peers-kp)
      (println)
      (println "Done.")
      (println (format "  cd %s   # keys + configs are here" out-dir))
      (println "  See README.txt for how to deploy each peer's config.")
      (println (format "  To add another peer later: just wireguard-add-peer %s" out-dir)))))

(defn add-peer-wizard
  "Interactive `wireguard-add-peer`: load an existing wireguard-init output
  directory via its .wg-state.edn, prompt for one new peer, back up the
  existing files, and regenerate every peer's config (so the new peer is
  fully connected). Then rewrite the state file and offer to apply any
  changed configs to matching machines/<name>/wireguard.conf entries."
  [cfg out-dir-arg]
  (println "WireGuard add-peer wizard")
  (println "  Adds one peer to an existing wireguard-init output directory.")
  (println "  Every peer's config is regenerated so the new peer is fully connected;")
  (println "  the previous files are moved into a backup-<timestamp>/ subdir first.")
  (println)
  (let [out-dir (or (not-empty (str/trim (or out-dir-arg "")))
                    (let [default (detect-latest-out-dir)
                          msg (if default
                                (format "Existing WireGuard output directory [%s]:" default)
                                "Existing WireGuard output directory:")
                          v (str/trim (prompt/ask msg (or default "")))]
                      (when (str/blank? v)
                        (println "Error: an output directory is required.")
                        (System/exit 1))
                      v))
        state (load-state-or-exit! out-dir)
        subnet (parse-cidr (:subnet state))
        topology (:topology state)
        existing (vec (:peers state))]
    (println)
    (println (format "Loaded: %s" (state-path out-dir)))
    (println (format "  Subnet:   %s" (:subnet state)))
    (println (format "  Topology: %s" (name topology)))
    (println (format "  Peers:    %d" (count existing)))
    (doseq [p existing] (println (summarize-peer p)))
    (println)
    (println "── New peer ──────────────────────────")
    (let [new-peer (ask-peer subnet topology existing)]
      (println (summarize-peer new-peer))
      (println)
      (println "Plan:")
      (println (format "  Add:      %s" (:name new-peer)))
      (println (format "  Regen:    every peer in %s (%d file(s))" out-dir (inc (count existing))))
      (println (format "  Backup:   %s/backup-<timestamp>/" out-dir))
      (println)
      (when-not (prompt/confirm "Proceed?" :yes)
        (println "Aborted.")
        (System/exit 0))
      (println)
      (println "Generating keypair for new peer...")
      (let [new-kp (merge new-peer (generate-keypair! cfg))
            existing-hydrated (mapv #(rehydrate-peer! out-dir %) existing)
            all-peers (conj existing-hydrated new-kp)
            backup-dir (backup-existing! out-dir)]
        (when backup-dir
          (println (format "  backed up previous files -> %s" backup-dir)))
        (println (format "Writing configs to %s" out-dir))
        (write-all! out-dir subnet topology all-peers)
        (offer-apply! cfg out-dir all-peers)
        (println)
        (println "Done.")
        (println (format "  New peer:  %s (%s)" (:name new-kp) (:address new-kp)))
        (println (format "  Backup:    %s" (or backup-dir "(nothing to back up)")))
        (println "  Existing peers' configs also changed — redeploy any peers you didn't apply.")))))
      

