# Extra hosts module - adds custom /etc/hosts entries from /var/identity
#
# This module:
# 1. Creates a placeholder /etc/hosts file
# 2. At boot, reads /var/identity/hosts if present
# 3. Combines base entries (localhost) with custom entries
# 4. Bind mounts the combined file over /etc/hosts
#
# Place extra host entries in machines/<name>/hosts, one per line like /etc/hosts.
{ config, lib, pkgs, ... }:

{
  config = {
    # Disable NixOS's normal /etc/hosts management - we'll handle it ourselves
    environment.etc."hosts" = lib.mkForce {
      text = ''
        # Placeholder - replaced by bind mount from hosts-identity service
        127.0.0.1 localhost
        ::1 localhost
      '';
      mode = "0644";
    };

    # Bind mount /etc/hosts from /run/hosts (populated by hosts-identity service)
    fileSystems."/etc/hosts" = {
      device = "/run/hosts";
      options = [ "bind" "nofail" ];
      depends = [ "/" ];
    };

    # Service to build /etc/hosts at boot
    systemd.services.hosts-identity = {
      description = "Build /etc/hosts from /var/identity";
      wantedBy = [ "multi-user.target" ];
      before = [ "network.target" "nss-lookup.target" ];
      after = [ "local-fs.target" "var.mount" ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      script = ''
        # Get hostname from /var/identity
        hostname="nixos"
        if [ -f /var/identity/hostname ]; then
          hostname=$(cat /var/identity/hostname)
        fi

        # Build hosts file with base entries
        cat > /run/hosts << EOF
        # /etc/hosts - generated by hosts-identity
        127.0.0.1 localhost $hostname
        ::1 localhost $hostname

        # The following lines are desirable for IPv6 capable hosts
        ::1 ip6-localhost ip6-loopback
        fe00::0 ip6-localnet
        ff00::0 ip6-mcastprefix
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters
        ff02::3 ip6-allhosts
        EOF

        # Append extra hosts from /var/identity if present
        if [ -f /var/identity/hosts ] && [ -s /var/identity/hosts ]; then
          echo "" >> /run/hosts
          echo "# Extra hosts from /var/identity/hosts" >> /run/hosts
          # Filter out comments and empty lines for cleaner output, but keep all valid entries
          grep -v '^\s*#' /var/identity/hosts | grep -v '^\s*$' >> /run/hosts || true
        fi

        chmod 0644 /run/hosts
      '';
    };
  };
}
