# Extra hosts module - adds custom /etc/hosts entries from /var/identity
#
# This module:
# 1. Creates a placeholder /etc/hosts file in the base image
# 2. At boot, builds /run/hosts with hostname + extra hosts
# 3. Bind mounts /run/hosts over /etc/hosts
#
# Place extra host entries in machines/<name>/hosts, one per line like /etc/hosts.
{ config, lib, pkgs, ... }:

{
  config = {
    # Disable NixOS's normal /etc/hosts management - we'll handle it ourselves
    environment.etc."hosts" = lib.mkForce {
      text = ''
        # Placeholder - replaced by bind mount from hosts-identity service
        127.0.0.1 localhost
        ::1 localhost
      '';
      mode = "0644";
    };

    # Service to build and mount /etc/hosts at boot
    systemd.services.hosts-identity = {
      description = "Build /etc/hosts from /var/identity";
      wantedBy = [ "sysinit.target" ];
      before = [ "network-pre.target" "nss-lookup.target" ];
      after = [ "local-fs.target" "var.mount" ];
      wants = [ "local-fs.target" ];

      unitConfig = {
        DefaultDependencies = false;
      };

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      script = ''
        # Get hostname from /var/identity
        hostname="nixos"
        if [ -f /var/identity/hostname ]; then
          hostname=$(cat /var/identity/hostname)
        fi

        # Build hosts file with base entries
        cat > /run/hosts << EOF
# /etc/hosts - generated by hosts-identity
127.0.0.1 localhost $hostname
::1 localhost $hostname

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

        # Append extra hosts from /var/identity if present
        if [ -f /var/identity/hosts ] && [ -s /var/identity/hosts ]; then
          echo "" >> /run/hosts
          echo "# Extra hosts from /var/identity/hosts" >> /run/hosts
          # Filter out comments and empty lines for cleaner output, but keep all valid entries
          grep -v '^\s*#' /var/identity/hosts | grep -v '^\s*$' >> /run/hosts || true
        fi

        chmod 0644 /run/hosts

        # Bind mount over /etc/hosts
        ${pkgs.util-linux}/bin/mount --bind /run/hosts /etc/hosts
      '';
    };
  };
}
