# Syncthing profile
#
# Peer-to-peer file sync. Ports 22000/tcp+udp (sync) and 21027/udp (LAN
# discovery). Web GUI on 127.0.0.1:8384 (loopback only — front with traefik
# + wg-auth to expose it).
#
# Per-machine identity files (staged from machines/<name>/ into
# <identityDir>/ on the guest):
#
#   cert.pem, key.pem    — pinned device identity (device ID = hash of cert).
#                          Generated by `just create` and preserved across
#                          recreate. WITHOUT these two, syncthing would mint a
#                          fresh identity on every recreate.
#   syncthing_devices    — `<peer-name> <device-id> [addr]...`, one per line.
#                          Trailing addresses (tcp:// / quic:// / dynamic) pin
#                          where THIS device will try to reach that peer. Omit
#                          for automatic discovery (equivalent to `dynamic`).
#   syncthing_folders    — `<folder-id> <path> <peer-name>...`, one per line.
#
#   identityDir = /etc/syncthing         (proxmox-lxc)
#               = /var/identity/syncthing (KVM immutable)
#
# Both files are AUTHORITATIVE — the `syncthing-config` oneshot runs after
# syncthing.service is ready and reconciles running state to match:
# entries in the file are added if missing; entries in syncthing that are
# NOT in the file are deleted (including entries a user just pasted into
# the GUI). The local device and its membership in every folder are never
# removed. To remove a peer permanently: delete its line from
# `syncthing_devices` and run `just sync-identity <name>` (or
# `just upgrade <name>`) — same pattern as nas_acl / nas_hosts /
# wireguard.nft.
#
# Composes with the nas profile: when nas is present, syncthing runs as the
# shared `nas` user (uid 1500) so files under /srv/* have the same ownership
# as those written by Samba/NFS/copyparty. Otherwise, the default `syncthing`
# system user.
#
# Composes with the wireguard profile: at reconcile time syncthing-config
# checks for wg0. If it's up, syncthing is confined to the tunnel:
# listenAddresses = tcp+quic on the wg IP, and globalAnnounce / localAnnounce
# / relays / NAT-PMP are all disabled. Peers must be listed with pinned
# addresses (e.g. `tcp://<peer-wg-ip>:22000`) in syncthing_devices. Without
# wireguard, syncthing runs with its stock discovery/relay stack.
{ config, lib, pkgs, ... }:

let
  # nas.nix always enables services.samba (its only server); use that as the
  # "nas profile is in the build" signal, no extra option required.
  nasEnabled = config.services.samba.enable or false;
  identityDir = if config.vm.container then "/etc/syncthing"
                else "/var/identity/syncthing";
  syncUser = if nasEnabled then "nas" else "syncthing";
  syncGroup = if nasEnabled then "nas" else "syncthing";
in
{
  services.syncthing = {
    enable = true;
    user = syncUser;
    group = syncGroup;
    dataDir = "/var/lib/syncthing";
    # cert/key are copied into configDir at ExecStartPre; the local device ID
    # is derived from cert.pem, so this is what pins identity across recreate.
    cert = "${identityDir}/cert.pem";
    key = "${identityDir}/key.pem";
    guiAddress = "127.0.0.1:8384";
    # Firewall handled by tcp_ports / udp_ports in the machine config.
    openDefaultPorts = false;
    # Devices/folders are managed by syncthing-config from runtime files;
    # keep the nix-side reconciler off so it can't clobber them.
    overrideDevices = false;
    overrideFolders = false;
    settings = {
      # Turn off syncthing's built-in DNS-rebind/Host-header check. The GUI
      # normally rejects any request whose Host header isn't localhost/127.
      # Behind traefik + wg-required, the network gate has already
      # authenticated the peer, so the Host check is redundant AND blocks
      # the proxied route with "Host check error". Disabling it re-enables
      # DNS-rebind risk in principle — but the GUI is loopback-only and
      # every request has to survive wg-required first.
      gui.insecureSkipHostcheck = true;
    };
  };

  # When bundled with nas, syncthing shares that identity — the `nas` user
  # already exists (nas.nix). Otherwise the syncthing module creates its own
  # `syncthing` user with a nixpkgs-assigned uid.

  # syncthing-config: reconcile syncthing's running config to match the
  # per-machine devices/folders files. Authoritative: entries missing from a
  # file get deleted (except the local device and its own folder membership).
  systemd.services.syncthing-config = {
    description = "Reconcile syncthing devices/folders with per-machine files";
    # Order after syncthing-init so the nix-side gui/settings push (e.g.
    # insecureSkipHostcheck) settles before we start adding devices/folders.
    # `After=` on an absent unit is a no-op, so this is safe when
    # syncthing-init isn't emitted.
    # If the wireguard profile is also enabled, we bind syncthing to the wg
    # interface — so order after wg-quick-wg0.service so `ip addr show wg0`
    # returns the tunnel IP. Absent unit is a silent no-op.
    after = [ "syncthing.service" "syncthing-init.service" "wg-quick-wg0.service" ];
    wants = [ "wg-quick-wg0.service" ];
    requires = [ "syncthing.service" ];
    wantedBy = [ "multi-user.target" ];
    path = [ pkgs.syncthing pkgs.coreutils pkgs.gnused pkgs.gnugrep pkgs.iproute2 pkgs.curl ];
    # Point `syncthing cli` at the same config + data dirs the daemon is
    # running out of, so it can read cert.pem + config.xml (for the API
    # key) instead of falling back to ~/.local/state/syncthing (which
    # doesn't exist for the service user). STHOMEDIR sets both config and
    # data at once; the daemon defaults databaseDir=configDir, so this
    # matches.
    environment.STHOMEDIR = config.services.syncthing.configDir;
    serviceConfig = {
      Type = "oneshot";
      User = syncUser;
      Group = syncGroup;
      RemainAfterExit = true;
    };
    script = ''
      set -u
      devices_file=${identityDir}/syncthing_devices
      folders_file=${identityDir}/syncthing_folders

      clean() { sed -e 's/#.*//' "$1" 2>/dev/null | grep -vE '^[[:space:]]*$' || true; }
      in_set() { echo " $2 " | grep -qF " $1 "; }

      # Wait for syncthing REST API to answer (db migration on 1.x→2.x can
      # take a while — the healthy signal is `cli show system` returning 0).
      last_err=""
      for i in $(seq 1 60); do
        last_err=$(syncthing cli show system 2>&1 >/dev/null) && break
        sleep 1
      done

      # Local device ID: never delete, and never remove from any folder.
      local_id=$(syncthing cli show system 2>/dev/null \
                 | sed -nE 's/.*"myID":[[:space:]]*"([^"]+)".*/\1/p')
      if [ -z "$local_id" ]; then
        echo "syncthing-config: could not reach syncthing REST API after 60s" >&2
        echo "syncthing-config: STHOMEDIR=''${STHOMEDIR:-<unset>}" >&2
        echo "syncthing-config: last error from 'syncthing cli show system':" >&2
        echo "$last_err" >&2
        exit 1
      fi

      # API key + GUI URL for the /rest/db/scan trigger below. The address is
      # loopback-only by profile design, so no TLS. Grep the XML because the
      # daemon may not always be reachable via `cli show` under load (we're
      # explicitly avoiding round-tripping through it here).
      gui_addr=$(sed -nE 's|.*<gui[^>]*enabled=[^>]*>||; s|.*<address>([^<]+)</address>.*|\1|p' \
                 "$STHOMEDIR/config.xml" 2>/dev/null | head -1)
      [ -z "$gui_addr" ] && gui_addr=127.0.0.1:8384
      apikey=$(sed -nE 's|.*<apikey>([^<]+)</apikey>.*|\1|p' "$STHOMEDIR/config.xml" 2>/dev/null | head -1)

      # Helper: replace the entire ordered collection at PATH with the given
      # values. `syncthing cli config <path>` treats list-typed properties as
      # indexed collections with list/add/<i> delete — no atomic "set". Delete
      # highest-index first so remaining indices don't renumber under us.
      reset_collection() {
        local -a args
        # First N tokens up to the terminator are the path; rest are values.
        local -a path=()
        local -a values=()
        local saw_sep=""
        for tok in "$@"; do
          if [ -z "$saw_sep" ] && [ "$tok" = "--" ]; then saw_sep=1; continue; fi
          if [ -n "$saw_sep" ]; then values+=("$tok"); else path+=("$tok"); fi
        done
        local -a current
        mapfile -t current < <(syncthing cli config "''${path[@]}" list 2>/dev/null)
        local i
        for ((i=''${#current[@]}-1; i>=0; i--)); do
          syncthing cli config "''${path[@]}" "''${current[$i]}" delete 2>/dev/null || true
        done
        local v
        for v in "''${values[@]}"; do
          syncthing cli config "''${path[@]}" add "$v" 2>/dev/null || true
        done
      }

      # ── Listen addresses + discovery/relay/NAT ──
      # If wireguard is up: bind syncthing to the wg tunnel only, and turn
      # OFF anything that would let a peer find us or reach us off-tunnel —
      # global discovery (syncthing.net), local LAN broadcast, public
      # relays, and NAT-PMP/UPnP. Peers must know our wg IP and be routable
      # to it. If wireguard is NOT up: restore syncthing's defaults.
      set_bool() {
        # $1 = option key, $2 = "true"|"false"
        syncthing cli config options "$1" set "$2" 2>/dev/null || true
      }
      wg_ip=$(ip -4 -o addr show wg0 2>/dev/null \
              | sed -nE 's/.*inet ([0-9.]+)\/.*/\1/p' | head -1)
      if [ -n "$wg_ip" ]; then
        echo "syncthing-config: wg0 up ($wg_ip) — restricting to tunnel"
        reset_collection options raw-listen-addresses -- \
          "tcp://$wg_ip:22000" "quic://$wg_ip:22000"
        set_bool global-ann-enabled false
        set_bool local-ann-enabled  false
        set_bool relays-enabled     false
        set_bool natenabled         false
      else
        echo "syncthing-config: wg0 not present — restoring defaults"
        reset_collection options raw-listen-addresses -- default
        set_bool global-ann-enabled true
        set_bool local-ann-enabled  true
        set_bool relays-enabled     true
        set_bool natenabled         true
      fi

      # ── Devices ──
      declare -A id_of=()
      intended_devs=""
      if [ -f "$devices_file" ]; then
        while read -r name id rest; do
          [ -z "$name" ] && continue
          [ -z "$id" ] && continue
          id_of["$name"]="$id"
          intended_devs="$intended_devs $id"
          # rest = zero or more whitespace-separated addresses. Word-splitting
          # is intentional here — addresses don't contain whitespace.
          local_addrs=($rest)
          # First add (no-op if the device already exists — CLI is quiet on
          # duplicates). We'll authoritatively reset the addresses collection
          # right after regardless of add outcome.
          if [ ''${#local_addrs[@]} -gt 0 ]; then
            add_args=(--device-id "$id" --name "$name")
            for a in "''${local_addrs[@]}"; do add_args+=(--addresses "$a"); done
            syncthing cli config devices add "''${add_args[@]}" 2>/dev/null || true
            reset_collection devices "$id" addresses -- "''${local_addrs[@]}"
          else
            syncthing cli config devices add \
              --device-id "$id" --name "$name" 2>/dev/null || true
            # No addresses in the file = automatic discovery.
            reset_collection devices "$id" addresses -- dynamic
          fi
        done < <(clean "$devices_file")
      fi

      for id in $(syncthing cli config devices list 2>/dev/null); do
        [ "$id" = "$local_id" ] && continue
        if ! in_set "$id" "$intended_devs"; then
          echo "syncthing-config: removing device $id (not in $devices_file)"
          syncthing cli config devices "$id" delete 2>/dev/null || true
        fi
      done

      # ── Folders ── (authoritative on folder set AND each folder's peer set)
      intended_folders=""
      if [ -f "$folders_file" ]; then
        while read -r fid fpath rest; do
          [ -z "$fid" ] && continue
          [ -z "$fpath" ] && continue
          intended_folders="$intended_folders $fid"
          syncthing cli config folders add \
            --id "$fid" --path "$fpath" --label "$fid" 2>/dev/null || true

          dev_ids=""
          for peer in $rest; do
            pid="''${id_of[$peer]:-}"
            if [ -z "$pid" ]; then
              echo "syncthing-config: WARNING: folder '$fid' references unknown peer '$peer'" >&2
              continue
            fi
            dev_ids="$dev_ids $pid"
            syncthing cli config folders "$fid" devices add \
              --device-id "$pid" 2>/dev/null || true
          done

          for existing in $(syncthing cli config folders "$fid" devices list 2>/dev/null); do
            [ "$existing" = "$local_id" ] && continue
            if ! in_set "$existing" "$dev_ids"; then
              syncthing cli config folders "$fid" devices "$existing" delete 2>/dev/null || true
            fi
          done

          # Seed a default .stignore covering paths that share the folder tree
          # but shouldn't sync: copyparty's per-folder state (.hist, from the
          # nas profile) and syncthing's own versioning dir. Only written when
          # the file is missing, so user edits are preserved on re-runs. Trigger
          # a rescan when we just wrote it so a stale pull-error (e.g. a peer
          # deleting .hist while ours is non-empty) clears immediately.
          if [ -d "$fpath" ] && [ ! -e "$fpath/.stignore" ]; then
            cat > "$fpath/.stignore" <<'STIGNORE_EOF'
# Default ignore patterns installed by syncthing-config.
# Edit freely — this file is only written when missing; the profile
# will not overwrite user changes on subsequent runs.
#
# Copyparty per-folder state (from the `nas` profile).
.hist
# Syncthing's own versioning dir (created when versioning is enabled).
.stversions
STIGNORE_EOF
            echo "syncthing-config: seeded $fpath/.stignore"
            if [ -n "$apikey" ]; then
              curl -sS -X POST -H "X-API-Key: $apikey" \
                "http://$gui_addr/rest/db/scan?folder=$fid" >/dev/null || true
            fi
          fi

          echo "syncthing-config: folder '$fid' -> $fpath (peers:''${dev_ids:- (none)})"
        done < <(clean "$folders_file")
      fi

      for fid in $(syncthing cli config folders list 2>/dev/null); do
        if ! in_set "$fid" "$intended_folders"; then
          echo "syncthing-config: removing folder $fid (not in $folders_file)"
          syncthing cli config folders "$fid" delete 2>/dev/null || true
        fi
      done
    '';
  };

  # Fail closed: if syncthing-config fails (bad file, unknown peer, API
  # unreachable), stop syncthing rather than leave it running with stale
  # or divergent config. The reconciler talks to the REST API so it must
  # run AFTER syncthing.service (can't be a pre-start gate the way
  # nas-shares is for smbd/nfsd). So the flow is: syncthing starts → its
  # config is reconciled → on failure BindsTo tears syncthing back down.
  # Recovery: fix the offending file and `systemctl restart
  # syncthing-config` (its Requires= pulls syncthing back up first).
  systemd.services.syncthing.bindsTo = [ "syncthing-config.service" ];


  # Firewall ports are NOT opened in the image. Sync (22000) and discovery
  # (21027) are seeded commented into tcp_ports/udp_ports by init-machine so
  # operators explicitly opt in — matches the nas profile's pattern.

  environment.systemPackages = [ pkgs.syncthing ];
}
