# wg-auth: pre-authenticate wireguard peers by source IP and expose that
# identity to backend services as an X-Remote-User request header, via a pair
# of Traefik middlewares.
#
# Automatically included by the `traefik` profile — you don't enable this one
# directly. Effective only when wireguard is also enabled and a wg_users file
# maps peer names to user identities.
#
# ── Pieces ──────────────────────────────────────────────────────────────────
#   traefik-wg-users.service   oneshot generator. Reads wireguard.conf +
#                              wg_users → writes:
#                              /run/wg-auth/users.map        (auth service input)
#                              <dynDir>/wg-users.yml             (traefik middleware defs)
#                              Fail-closed: parse/validation errors leave both
#                              files removed, so routers referencing the
#                              middlewares fail to load (404) rather than
#                              silently falling through.
#
#   wg-auth.service            Go forward-auth daemon (pkgs.wg-auth). Reads
#                              /run/wg-auth/users.map, listens on
#                              127.0.0.1:9099, serves /lookup and /require.
#                              Runs as wg-auth:wg-auth (its own user + group).
#
# ── Middlewares exposed ─────────────────────────────────────────────────────
# The generator writes these two into the traefik dynamic dir; attach either
# to a router in your own dynamic config to opt that route in:
#
#   wg-user      Attach X-Remote-User when the source IP matches a mapped
#                wg peer. Unmapped peers pass through with no identity.
#   wg-required  Same, but 403 for unmapped peers (peers-only site).
#
# Both middlewares strip any client-supplied X-Remote-User before the auth
# step so a forged header can never survive.
#
# ── Fail-closed behaviors ───────────────────────────────────────────────────
#   - Auth service down → forwardAuth 5xx → Traefik 502
#   - Map I/O or parse error → wg-auth 500 → Traefik 502
#   - Generator failure (bad wg_users) → middleware YAML absent → routers
#     referencing wg-user / wg-required don't load → 404
#   - wireguard.conf absent → generator no-op → same 404 result
#
# ── Permissions ─────────────────────────────────────────────────────────────
#   /run/wg-auth/users.map        root:wg-auth 0640  (auth service reads)
#   <dynDir>/wg-users.yml            root:traefik 0644  (traefik reads)
#
# The traefik user has no access to the map, and the wg-auth user has no
# write access to anything the generator produces.

{ config, lib, pkgs, ... }:

let
  mutable  = config.vm.mutable;
  wgConf   = if mutable then "/etc/wireguard/wg0.conf"    else "/var/identity/wireguard.conf";
  wgUsers  = if mutable then "/etc/wg_users"              else "/var/identity/wg_users";
  dynDir   = if mutable then "/etc/traefik/dynamic"       else "/var/identity/traefik/dynamic";
  # Runtime dir owned by wg-auth. The map lives here (not under /run/traefik)
  # because traefik.service declares RuntimeDirectory=traefik, which creates
  # /run/traefik at 0700 root:traefik and blocks traversal for wg-auth even
  # if we chowned the map itself.
  mapFile  = "/run/wg-auth/users.map";
  midFile  = "${dynDir}/wg-users.yml";
  authAddr = "127.0.0.1:9099";

  wg-auth-pkg = pkgs.callPackage ../src/wg-auth/package.nix { };

  # Static middleware YAML — no per-VM data. The generator writes this verbatim
  # so the file's presence is coupled to a successful validation of wg_users +
  # wireguard.conf (fail-closed: bad input → no middleware defs → 404).
  middlewareYaml = ''
    # ${midFile} — generated by traefik-wg-users.service. Do NOT hand-edit.
    # Source: wireguard.conf + wg_users. Rebuild by re-running the service
    # (automatic on `sync-identity`) or `systemctl restart traefik-wg-users`.
    http:
      middlewares:
        # Attach X-Remote-User when the source IP is a known wg peer;
        # unmapped peers pass through with no identity asserted.
        wg-user:
          chain:
            middlewares: [wg-strip-user, wg-auth-lookup]

        # Same, but 403 for unmapped peers (peers-only site).
        wg-required:
          chain:
            middlewares: [wg-strip-user, wg-auth-require]

        # Belt-and-suspenders: clear any client-supplied X-Remote-User before
        # the auth step. aliasHeadersStrategy: delete handles X_Remote_User →
        # X-Remote-User aliases; this handles the canonical form.
        wg-strip-user:
          headers:
            customRequestHeaders:
              X-Remote-User: ""

        wg-auth-lookup:
          forwardAuth:
            address: "http://${authAddr}/lookup"
            authResponseHeaders: [X-Remote-User]

        wg-auth-require:
          forwardAuth:
            address: "http://${authAddr}/require"
            authResponseHeaders: [X-Remote-User]
  '';
in
{
  users.users.wg-auth = {
    isSystemUser = true;
    group = "wg-auth";
    description = "wg-auth forward-auth service";
  };
  users.groups.wg-auth = { };

  # Pre-seed an empty deny-mode map before any consumer starts. The generator
  # rewrites this immediately after boot; if it fails validation, /lookup +
  # /require return 500 (empty map is not the same as an error — see below —
  # but a missing map file IS an error, which is what tmpfiles prevents).
  systemd.tmpfiles.rules = [
    "d /run/wg-auth 0755 root wg-auth -"
  ];

  systemd.services.traefik-wg-users = {
    description = "Generate wg-auth peer→user map + Traefik middleware YAML";
    wantedBy = [ "multi-user.target" ];
    after = [ "wg-quick-wg0.service" ] ++ lib.optional (!mutable) "var.mount";
    wants = [ "wg-quick-wg0.service" ];
    path = with pkgs; [ coreutils gawk gnused gnugrep ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      set -u
      wg_conf=${wgConf}
      wg_users=${wgUsers}
      map=${mapFile}
      mid=${midFile}
      dyn=${dynDir}

      # Fail-closed removal: if we can't produce a valid pair, take both files
      # away so routers referencing the middlewares stop loading.
      teardown() {
        rm -f "$map" "$mid" 2>/dev/null || true
      }

      # No wg config -> nothing to map. Emit no middleware YAML either, so
      # routers referencing wg-user/wg-required fail to load (fail-closed).
      if [ ! -f "$wg_conf" ]; then
        teardown
        echo "traefik-wg-users: no $wg_conf; wg-user/wg-required middlewares disabled."
        exit 0
      fi

      # ── parse wg0.conf: peer name -> space-separated IPs (/32 only) ──────
      declare -A peer_ips=()
      section=""
      cur_name=""
      cur_ips=""
      flush() {
        if [ -n "$cur_name" ] && [ -n "$cur_ips" ]; then
          peer_ips[$cur_name]="''${cur_ips# }"
        fi
        cur_name=""
        cur_ips=""
      }
      while IFS= read -r line || [ -n "$line" ]; do
        line="''${line#"''${line%%[![:space:]]*}"}"
        line="''${line%"''${line##*[![:space:]]}"}"
        case "$line" in
          "[Interface]") flush; section=interface ;;
          "[Peer]")      flush; section=peer ;;
          "#"*)
            hn=$(printf '%s\n' "$line" | sed -nE 's/^#[[:space:]]*hostname:[[:space:]]*(.+)$/\1/p')
            if [ -n "$hn" ] && [ "$section" = peer ]; then
              cur_name="$hn"
            fi
            ;;
          "") ;;
          *=*)
            key=$(printf '%s\n' "$line" | sed -nE 's/^([^=[:space:]]+)[[:space:]]*=.*/\1/p')
            val=$(printf '%s\n' "$line" | sed -nE 's/^[^=]+=[[:space:]]*(.+)$/\1/p')
            if [ "$section" = peer ] && [ "$key" = AllowedIPs ]; then
              for a in $(printf '%s' "$val" | tr ',' ' '); do
                a=$(printf '%s' "$a" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
                # Only take single-host entries. Skip subnets (a /24 to a
                # single wg peer means "route this subnet through this peer",
                # not "this peer's identity is any IP in this subnet").
                case "$a" in
                  *:*) ;;              # skip IPv6 for now
                  */32)  cur_ips="$cur_ips ''${a%/32}" ;;
                  *[!0-9.]*) ;;         # not an IPv4
                  */*) ;;               # non-/32 CIDR: skip
                  *)   cur_ips="$cur_ips $a" ;;   # bare IP
                esac
              done
            fi
            ;;
        esac
      done < "$wg_conf"
      flush

      # ── read wg_users, validate, and emit the map ────────────────────────
      # Missing/empty wg_users is a valid state (empty map). Parse errors or
      # unknown peer names are fatal (fail-closed).
      errors=""
      declare -A user_by_peer=()
      if [ -f "$wg_users" ]; then
        line_no=0
        while IFS= read -r raw || [ -n "$raw" ]; do
          line_no=$((line_no + 1))
          line=$(printf '%s' "$raw" | sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          [ -z "$line" ] && continue
          # positional split
          set -- $line
          if [ "$#" -ne 2 ]; then
            errors="$errors"$'\n'"traefik-wg-users: ERROR: $wg_users line $line_no: expected `<wg-peer> <user>`, got: $line"
            continue
          fi
          peer="$1"; user="$2"
          if [ -z "''${peer_ips[$peer]:-}" ]; then
            errors="$errors"$'\n'"traefik-wg-users: ERROR: $wg_users line $line_no: wg peer '$peer' not found in $wg_conf (or has no /32 AllowedIPs)"
            continue
          fi
          user_by_peer[$peer]="$user"
        done < "$wg_users"
      fi

      if [ -n "$errors" ]; then
        printf '%s\n' "$errors" >&2
        echo "traefik-wg-users: pre-flight failed; wg-user/wg-required middlewares disabled." >&2
        teardown
        exit 1
      fi

      # ── emit atomically ──────────────────────────────────────────────────
      map_tmp=$(mktemp "$map.XXXXXX")
      {
        echo "# generated by traefik-wg-users.service — do not edit"
        echo "# source: $wg_conf + $wg_users"
        for peer in "''${!user_by_peer[@]}"; do
          user="''${user_by_peer[$peer]}"
          for ip in ''${peer_ips[$peer]}; do
            printf '%s\t%s\n' "$ip" "$user"
          done
        done
      } > "$map_tmp"
      chown root:wg-auth "$map_tmp"
      chmod 0640 "$map_tmp"
      mv -f "$map_tmp" "$map"

      # The dynamic dir might not exist yet on a fresh VM whose user hasn't
      # staged a traefik/ subtree — in that case the traefik service is a
      # no-op anyway (ConditionPathExists on traefik.yml). Create it best-
      # effort so a later user-supplied traefik.yml picks up the middleware
      # without a reboot.
      mkdir -p "$dyn"
      mid_tmp=$(mktemp "$mid.XXXXXX")
      cat > "$mid_tmp" <<'YAML'
      ${middlewareYaml}
      YAML
      chown root:traefik "$mid_tmp" 2>/dev/null || true
      chmod 0644 "$mid_tmp"
      mv -f "$mid_tmp" "$mid"

      # Non-fatal count for the log.
      n_peers=''${#user_by_peer[@]}
      echo "traefik-wg-users: $n_peers wg peer(s) mapped; map=$map middlewares=$mid"
    '';
  };

  systemd.services.wg-auth = {
    description = "wg-auth: IP → wg-peer-user forward-auth service";
    wantedBy = [ "multi-user.target" ];
    after = [ "traefik-wg-users.service" ];
    requires = [ "traefik-wg-users.service" ];
    serviceConfig = {
      ExecStart = "${wg-auth-pkg}/bin/wg-auth -addr ${authAddr} -map ${mapFile}";
      User = "wg-auth";
      Group = "wg-auth";
      Restart = "on-failure";
      RestartSec = 2;
      # No write access to anything: the service is a pure reader.
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      NoNewPrivileges = true;
      # Bind loopback only; deny any other network.
      RestrictAddressFamilies = [ "AF_UNIX" "AF_INET" "AF_INET6" ];
      IPAddressAllow = [ "127.0.0.0/8" "::1/128" ];
      IPAddressDeny = [ "any" ];
    };
  };

  # Make traefik-wg-users a soft dep of traefik so on boot the middleware
  # YAML is on disk before traefik starts scanning the dynamic dir. It's only
  # a nice-to-have (traefik hot-reloads) but avoids a startup-order flap.
  systemd.services.traefik = lib.mkIf config.services.traefik.enable {
    after = [ "traefik-wg-users.service" ];
    wants = [ "traefik-wg-users.service" ];
  };
}
